/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI.thucdon;

import DAO.ThucDonDao;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class UpdateGiaMon extends javax.swing.JFrame {

    private ThucDon parentForm; // Tham chiếu đến form ThucDon

    // Constructor và các phương thức khác ở trên
    // Phương thức setter để thiết lập tham chiếu đến form ThucDon
    public void setParentForm(ThucDon parentForm) {
        this.parentForm = parentForm;
    }
    int idmonan;

    /**
     * Creates new form UpdateGiaMon
     */
    public UpdateGiaMon(int idmon) {
        idmonan = idmon;
        initComponents();
        setTitle("Sửa giả món ăn");
        setLocationRelativeTo(null);
        setResizable(false);
        LoadGiaUpdate(idmonan);
    }

    private void LoadGiaUpdate(int id) {
        ThucDonDao thucdon = new ThucDonDao();
        String giacamon = thucdon.getGiaTheoMon(id);
        txtShowPrice.setText(giacamon);
    }

    private boolean isValidPrice(String price) {
        try {
            double value = Double.parseDouble(price);
            return value >= 0; // Giá phải lớn hơn hoặc bằng 0
        } catch (NumberFormatException e) {
            // Nếu không thể chuyển đổi sang số, giá không hợp lệ
            return false;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtShowPrice = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        btnHuyUpdate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Giá món");

        txtShowPrice.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        btnUpdate.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnUpdate.setText("Xác nhận");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnHuyUpdate.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnHuyUpdate.setText("Hủy");
        btnHuyUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnUpdate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnHuyUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtShowPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtShowPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdate)
                    .addComponent(btnHuyUpdate))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHuyUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyUpdateActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnHuyUpdateActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        String update = txtShowPrice.getText();
        ThucDonDao thucdon = new ThucDonDao();
        boolean isSuccess = thucdon.UpdateGiaTheoMon(idmonan, update);
        if (isSuccess) {
            JOptionPane.showMessageDialog(this, "Cập nhật giá thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            // Cập nhật lại dữ liệu trên bảng
            if (parentForm != null) {
                parentForm.loadThucDon(new ThucDonDao().laydanhsachthucdon());
//                System.out.println("Xin chào");
            }
            // Đóng form
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Lỗi! Không thể cập nhật giá.", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(UpdateGiaMon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(UpdateGiaMon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(UpdateGiaMon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(UpdateGiaMon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new UpdateGiaMon().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHuyUpdate;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtShowPrice;
    // End of variables declaration//GEN-END:variables
}
